name: ssh deploy
on:
  push:
    tags:        
      - v*

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh
      run: echo "$SSH_PRIVATE_KEY" > pkey && chmod og-rwx pkey && ssh -i pkey -o StrictHostKeyChecking=no "$SSH_SERVER" ./update-wbo.sh
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_SERVER: ${{ secrets.SSH_SERVER }}
